name: deploy to npm
on:
  push:
    branches:
      - master


jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: install
        run: |
          yarn install
      - name: publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          npm publish --access public
